### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sisanek** [AkitaAttribute/GetSteamoddedAHK#1]
Does anybody knows why I cannot fint Injector.exe in folder where it should be?

**Comment by AkitaAttribute** [comment]
Attach some screenshots of what you're trying to do, and I can tell ya.

**Comment by sisanek** [comment]
The folder where it should be it's nowhere to be found and about the screenshot it's liitle bit harder because I don't have right bottons on my keyboard for some reason
- "download_steamodded.exe" made folder as it should
- and didn't create "injector.exe"
so do you know what can I do with it?

**Comment by AkitaAttribute** [comment]
> The folder where it should be it's nowhere to be found and about the screenshot it's liitle bit harder because I don't have right bottons on my keyboard for some reason
> 
> * "download_steamodded.exe" made folder as it should
> * and didn't create "injector.exe"
>   so do you know what can I do with it?

My exe made a folder?  What folder?  Did you get a success popup like in my video?  If you don't have the rights to take a screenshot, I have concerns that you won't have the rights to use the exe properly.

**Comment by sisanek** [comment]
![screenshot](https://github.com/AkitaAttribute/GetSteamoddedAHK/assets/167011916/520290e4-5547-4481-80bc-df9b89ba643a)

**Comment by AkitaAttribute** [comment]
> ![screenshot](https://private-user-images.githubusercontent.com/167011916/322292281-520290e4-5547-4481-80bc-df9b89ba643a.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTY3NTMsIm5iZiI6MTcxMzExNjQ1MywicGF0aCI6Ii8xNjcwMTE5MTYvMzIyMjkyMjgxLTUyMDI5MGU0LTU1NDctNDQ4MS04MGJjLWRmOWI4OWJhNjQzYS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQxNzQwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTI3Y2FmYmRmYjZlNjhjYjA3ZDVjNTQ0MmRkNWM3MGJiNWVhNzQxZDRkMWZiOGFjYTcwMGUwOGI2ZmEwMjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WHkwvBkWhobEtwZwMhz_g4PQ-Vz5wyhPnEzMvEo2xkg)

So that's just the normal Balatro folder.  When you run my exe, does anything pop up?

**Comment by sisanek** [comment]
you mean download_steamodded.exe?

**Comment by sisanek** [comment]
if then it says this
![Výstřižek2](https://github.com/AkitaAttribute/GetSteamoddedAHK/assets/167011916/5a46dbaa-d6db-4e36-bb3c-a628cb2c1860)

**Comment by AkitaAttribute** [comment]
> you mean download_steamodded.exe?

Yes.  When you run that exe, does anything pop up?  Does it ask you for administrator permissions?  Does it tell you a folder location?

**Comment by AkitaAttribute** [comment]
Oh.  You're on Windows 7, aren't you.  I haven't tested it on Windows 7.  I can do that later today.

**Comment by sisanek** [comment]
oh okey

**Comment by sisanek** [comment]
and any idea what should I do with it?

**Comment by AkitaAttribute** [comment]
> and any idea what should I do with it?

It should work if you download it again.  If not, I will actually need to test it.  I replaced the CURL command with a powershell one that should work on Windows 7.

**Comment by sisanek** [comment]
I was now trying it and it told me that it failed
![Výstřižek](https://github.com/AkitaAttribute/GetSteamoddedAHK/assets/167011916/e01d2156-c342-4066-bfac-62cd759765b0)

**Comment by AkitaAttribute** [comment]
> I was now trying it and it told me that it failed ![Výstřižek](https://private-user-images.githubusercontent.com/167011916/322308755-e01d2156-c342-4066-bfac-62cd759765b0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMjc3MDgsIm5iZiI6MTcxMzEyNzQwOCwicGF0aCI6Ii8xNjcwMTE5MTYvMzIyMzA4NzU1LWUwMWQyMTU2LWMzNDItNDA2Ni1iZmFjLTYyY2Q3NTk3NjViMC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQyMDQzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzViN2YyMWY4MDQ2YTVlZTE0YTNmZjJhZjAzNWNjNjQ0YWQyOTk5ZjU0OTdkMGFjZDVkODViZmU1MzIxYTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OFT-pGgfzH-Hr-gV37vZVNI5-kWjEUNddacPo7qjqAs)

Yeah, I'll need to test it more on Windows 7.

**Comment by sisanek** [comment]
Okey, just please let me know when you got it

**Comment by AkitaAttribute** [comment]
> Okey, just please let me know when you got it

So I can't get Balatro to run on Windows 7, partially because Steam seems to have dropped support for Windows 7 as of this year.  That being said, if you have it working, I should be able to get the script to work regardless of Balatro being installed.  I'm gonna get it fixed today.

**Comment by sisanek** [comment]
Okey thank you

**Comment by AkitaAttribute** [comment]
> Okey thank you

Can you open a powershell window and run this command "$PSVersionTable.PSVersion" without the quotes, and send me a screenshot of the results?

**Comment by sisanek** [comment]
I'm turning on my Computer so if you wait like 2-3 minutes then I'll try it

**Comment by sisanek** [comment]
this is what happened
![Výstřižek](https://github.com/AkitaAttribute/GetSteamoddedAHK/assets/167011916/6187b75d-1814-486b-b948-86254276eb09)

**Comment by AkitaAttribute** [comment]
> this is what happened ![Výstřižek](https://private-user-images.githubusercontent.com/167011916/322515899-6187b75d-1814-486b-b948-86254276eb09.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTEzNTcsIm5iZiI6MTcxMzE5MTA1NywicGF0aCI6Ii8xNjcwMTE5MTYvMzIyNTE1ODk5LTYxODdiNzVkLTE4MTQtNDg2Yi1iOTQ4LTg2MjU0Mjc2ZWIwOS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNDI0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODU4NDY1YjlkY2YxNWVlOTllMjI1YWJhNjZhZjExNWNmYjM3NzE2OWI5ZjY3YTk0MmVlZmEzNzJkZTRhYzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xOKM7pADHQr82lm5QUqdSNeoWhVL9L62Pb6VY4-lZww)

I'm asking if you can hit your Windows key, type in "Powershell", hit enter, then paste $PSVersionTable.PSVersion into the blue window.

**Comment by sisanek** [comment]
ill try few things to do with internet connetion

**Comment by AkitaAttribute** [comment]
> ill try few things to do with internet connetion

It's not your internet.  That's a bad error message generated from ChatGPT lol.

**Comment by sisanek** [comment]
> > this is what happened ![Výstřižek](https://private-user-images.githubusercontent.com/167011916/322515899-6187b75d-1814-486b-b948-86254276eb09.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTEzNTcsIm5iZiI6MTcxMzE5MTA1NywicGF0aCI6Ii8xNjcwMTE5MTYvMzIyNTE1ODk5LTYxODdiNzVkLTE4MTQtNDg2Yi1iOTQ4LTg2MjU0Mjc2ZWIwOS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNDI0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODU4NDY1YjlkY2YxNWVlOTllMjI1YWJhNjZhZjExNWNmYjM3NzE2OWI5ZjY3YTk0MmVlZmEzNzJkZTRhYzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xOKM7pADHQr82lm5QUqdSNeoWhVL9L62Pb6VY4-lZww)
> 
> I'm asking if you can hit your Windows key, type in "Powershell", hit enter, then paste $PSVersionTable.PSVersion into the blue window.

sorry i haven't used that yet ever

**Comment by AkitaAttribute** [comment]
> sorry i haven't used that yet ever

I understand, but it will help me craft this to work for you.  My version is very outdated, and I'm hoping yours may be updated.  

Alternatively, can you put this into your internet browser and see if it will download for you to skip this whole process?

https://github.com/Steamopollys/Steamodded/releases/latest/download/steamodded_injector.exe

**Comment by sisanek** [comment]
did you meant that?
![Výstřižek](https://github.com/AkitaAttribute/GetSteamoddedAHK/assets/167011916/86c0899b-fd4f-4b90-8e2e-7d8d761b7508)

**Comment by AkitaAttribute** [comment]
> did you meant that? ![Výstřižek](https://private-user-images.githubusercontent.com/167011916/322517842-86c0899b-fd4f-4b90-8e2e-7d8d761b7508.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxOTE2ODcsIm5iZiI6MTcxMzE5MTM4NywicGF0aCI6Ii8xNjcwMTE5MTYvMzIyNTE3ODQyLTg2YzA4OTliLWZkNGYtNGI5MC04ZTJlLTdkOGQ3NjFiNzUwOC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxNDI5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzY4MzdhODdkYTJmMjZhYmE0ODM5MGIzZDk2MmJhZWRlOWQ0NzViN2FiNDMzMDg5ZDgyNzE5ZmVlZjlkYmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tchhmCx3hjjw9OtXNop_N47rp8HI82mlRLk6WaLa1Ic)

Yeah, I may not be able to make this work for you.  I spent an hour trying to get a version that would work for Powershell 2.0 (which is the same as what I have).  I can try to help you manually do this, but it's not going to be as easy as my exe.  We can likely get it to work if you're willing to spend some time on it.

**Comment by AkitaAttribute** [comment]
I created a Windows 7 virtual machine just to try to get this working for you lol

**Comment by sisanek** [comment]
I have time to spend and nothing better to do so if you willing to help me

**Comment by AkitaAttribute** [comment]
> I have time to spend and nothing better to do so if you willing to help me

Sure.  My first question is if you can download directly from https://github.com/Steamopollys/Steamodded/releases/latest/download/steamodded_injector.exe

**Comment by sisanek** [comment]
for some reason Chrom and also my antivirus activated on it

**Comment by AkitaAttribute** [comment]
> for some reason Chrom and also my antivirus activated on it

Before we move to more complex things, can you try to download it from Internet Explorer instead of Chrome?

**Comment by sisanek** [comment]
wait a second I have to turn off my antivirus for that

**Comment by sisanek** [comment]
or not well at least I got it

**Comment by AkitaAttribute** [comment]
> or not well at least I got it

Great.  Move that file to your Balatro install location.  You can find that with Steam.  (You can see how to do this with my video).  We basically just skipped to after running my exe.

**Comment by sisanek** [comment]
well to tell the truth I have got any futher :D

**Comment by AkitaAttribute** [comment]
> well to tell the truth I have got any futher :D

I'm not sure I understand, but your happy face says you may have successfully modded it?

**Comment by sisanek** [comment]
yeah sorry my bad that should have been havn't

**Comment by AkitaAttribute** [comment]
> yeah sorry my bad that should have been havn't

Just to be clear, do you need additional help?  I can walk you through next steps if you do.

**Comment by sisanek** [comment]
well now I feel like an idiot because my PC cannot find some .dll that he have and I know that he have it -_-
but yeah the injector itself is working

**Comment by AkitaAttribute** [comment]
> well now I feel like an idiot because my PC cannot find some .dll that he have and I know that he have it -_- but yeah the injector itself is working

Alright, I'm glad I was able to guide you to that.  Good luck with the DLL issues.  I personally couldn't figure out how to get it to run on Windows 7 between Steam not working, and it being nearly impossible to get my certificates right. 

I'm going to close this issue.  Feel free to reach out if you have any other issues.
